### ISSUE TITLE
Composer.json not found

### ISSUE THREAD

**Issue by JamborJan** [zarvox/vagrant-spk#4]
In this file https://github.com/zarvox/vagrant-spk/blob/master/vagrant-spk

This:
```
set -eu

cd /opt/app

if [ -f /opt/app/composer.json ] ; then
    if [ ! -f composer.phar ] ; then
        curl -sS https://getcomposer.org/installer | php
    fi
    php composer.phar install
fi
```
doesn't work. The system is missing the json file because it is in ```/opt/app/frontend/composer.json``` at least for my paperwork port. Not sure how it is with other apps.
In my case it must be:
```
set -eu

cd /opt/app

if [ -f /opt/app/frontend/composer.json ] ; then
    if [ ! -f composer.phar ] ; then
        curl -sS https://getcomposer.org/installer | php
    fi
    cd /opt/app/frontend
    php ../composer.phar install
    php ../composer.phar self-update
fi
```
Will send a PR, feel free to reject it if this is only about my port.

**Comment by zarvox** [comment]
Thanks for the report!

I'm inclined to provide a default path at the root of the project, unless PHP projects tend to standardize on the `frontend/` convention.  For instance, Piwik, which also uses composer, keeps composer.json in the root of their source tree.

My goal is for `vagrant-spk` to provide some sane defaults, but I pragmatically expect that most projects will need to adjust their stack's shell scripts slightly to deal with where they keep data in their repo.  That's okay!

I'll note that the call to `php composer.phar self-update` is probably a good idea, though, so I may add that to the baseline script `vagrant-spk` provides.

**Comment by paulproteus** [comment]
Perhaps it'd be smart to add a composer.json to e.g.
https://github.com/zarvox/php-app-to-package-for-sandstorm so people can
see how that works.

**Comment by JamborJan** [comment]
I'm not quite sure. There is composer as dependency manager for php, npm is for node stuff, other things are for other frameworks. Maybe it would be better to add a commented info that such things must go in the build.sh and maybe we add the different examples there so that users can uncomment what they need?

**Comment by zarvox** [comment]
Sorry if I was unclear; I meant "add the call to self-update to the vagrant-spk-provided build script for the LEMP stack."  The build script can and should vary by stack, and indeed, it does in the source. :)

You make a good point though - some projects will wind up using a multitude of packages, so maybe these should act more like mixins.  Hrm.  Food for thought.

And yeah, it's probably a good idea to add some documentation indicating how vagrant-spk works, and where you should expect to make changes based on the codebase you're trying to use it with.

**Comment by JamborJan** [comment]
My opinion:
- it makes no sense to add more examples in the code as it will be useless for most of the users
- we should add use-cases where we point to the repo using vagrant-spk and highlight the main things added to make it run
- From my point of view this should be okay to be on the read-me

I will make a suggestion via PR.

**Comment by zarvox** [comment]
Since we've merged the improved README, including suggestions for what to modify, and where, I think we can probably close this issue now.  Feel free to reopen if I've missed something! :)
